/**
 * The API answers in error codes so that both front ends can word them their own way. This is
 * the website's way.
 */
const MESSAGES: Record<string, string> = {
    username_required: 'Un nom est nécessaire.',
    username_too_short: 'Trois caractères au minimum.',
    username_too_long: 'Trente-deux caractères au maximum.',
    username_invalid_characters: 'Lettres, chiffres, tiret et tiret bas uniquement.',
    username_already_used: 'Ce nom est déjà pris.',
    email_required: 'Une adresse est nécessaire.',
    email_invalid: 'Cette adresse ne ressemble pas à une adresse.',
    email_too_long: 'Cette adresse est trop longue.',
    email_already_used: 'Un compte existe déjà avec cette adresse.',
    password_required: 'Un mot de passe est nécessaire.',
    password_too_short: 'Huit caractères au minimum.',
    password_missing_lowercase: 'Il manque une minuscule.',
    password_missing_uppercase: 'Il manque une majuscule.',
    password_missing_digit: 'Il manque un chiffre.',
    password_missing_special_character: 'Il manque un caractère spécial.',
    title_required: 'Une quête a besoin d’un nom.',
    title_too_long: 'Deux cent cinquante-cinq caractères au maximum.',
    description_too_long: 'Description trop longue.',
    due_date_invalid: 'Date attendue au format AAAA-MM-JJ.',
    tag_too_long: 'Trente-deux caractères au maximum par étiquette.',
    priority_not_found: 'Ce rang n’existe pas.',
    category_not_found: 'Cette catégorie n’existe pas.',
    parent_task_not_found: 'La quête parente est introuvable.',
    parent_task_is_a_subtask: 'Une sous-quête ne peut pas en porter d’autres.',
    task_has_open_subtasks: 'Une sous-quête est encore ouverte.',
    label_required: 'Un nom est nécessaire.',
    label_too_long: 'Trente-deux caractères au maximum.',
    category_label_already_used: 'Une catégorie porte déjà ce nom.',
    category_not_editable: 'Une catégorie commune ne se modifie pas.',
    category_in_use: 'Des quêtes y sont encore rangées.',
    volume_invalid: 'Entre 1 et 5000 millilitres.',
    weight_invalid: 'Entre 20 et 400 kilogrammes.',
    bedtime_required: 'L’heure du coucher est nécessaire.',
    bedtime_invalid: 'Heure attendue au format HH:MM.',
    wake_up_time_required: 'L’heure du lever est nécessaire.',
    wake_up_time_invalid: 'Heure attendue au format HH:MM.',
    mood_rating_invalid: 'Note attendue entre 1 et 5.',
    sleep_too_short: 'Trente minutes au minimum.',
    sleep_too_long: 'Seize heures au maximum — vérifie l’heure du coucher.',
    action_failed: 'Le System n’a pas pu le faire. Réessaie dans un instant.',
    workout_already_in_progress: 'Une séance est déjà en cours.',
    workout_empty: 'Une séance se termine avec au moins une série.',
    workout_has_incomplete_sets: 'Une série n’est pas encore validée : valide-la ou supprime-la.',
    workout_finished: 'La séance est terminée : ses séries sont toutes faites.',
    name_too_long: 'Cent vingt-huit caractères au maximum.',
    note_too_long: 'Cinq mille caractères au maximum.',
    feeling_invalid: 'Ressenti attendu entre 1 et 5.',
    movement_ids_required: 'Choisis au moins un mouvement.',
    movement_ids_too_many: 'Six mouvements au maximum par bloc.',
    movement_unavailable: 'Ce mouvement n’est plus proposé.',
    block_ids_mismatch: 'La séance a changé entre-temps. Recharge la page.',
    reps_required: 'Le nombre de répétitions est nécessaire.',
    reps_not_tracked: 'Ce mouvement ne compte pas les répétitions.',
    reps_invalid: 'Entre 1 et 10000 répétitions.',
    weight_required: 'La charge est nécessaire.',
    load_invalid: 'Entre 0 et 1000 kilogrammes.',
    weight_not_tracked: 'Ce mouvement ne porte pas de charge.',
    duration_required: 'La durée est nécessaire.',
    duration_not_tracked: 'Ce mouvement ne se chronomètre pas.',
    duration_invalid: 'Entre 1 seconde et 24 heures.',
    distance_required: 'La distance est nécessaire.',
    distance_not_tracked: 'Ce mouvement ne mesure pas de distance.',
    distance_invalid: 'Entre 1 et 1000000 mètres.',
    rpe_invalid: 'RPE attendu entre 1 et 10, par demi-points.',
    set_type_unknown: 'Ce type de série n’existe pas.',
    set_type_inactive: 'Ce type de série n’est plus proposé.',
}

export function humanise(code: string): string {
    return MESSAGES[code] ?? code
}
